wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.7
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    m:
    - 1: trainer/global_step
      6:
      - 3
    - 1: train/loss
      5: 1
      6:
      - 1
    - 1: epoch
      5: 1
      6:
      - 1
    python_version: 3.10.8
    start_time: 1673014048.621278
    t:
      1:
      - 1
      - 9
      - 41
      - 49
      - 55
      - 71
      2:
      - 1
      - 9
      - 41
      - 49
      - 55
      - 71
      3:
      - 7
      - 13
      - 23
      4: 3.10.8
      5: 0.13.7
      8:
      - 3
      - 5
