steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/mlops-butterflies/testing', '.', '--build-arg', 'WANDB_API_KEY=$$wandbkey']
  secretEnv: ['wandbkey']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/mlops-butterflies/testing']
availableSecrets:
  secretManager:
  - versionName: projects/mlops-butterflies/secrets/wandb-key/versions/1
    env: 'wandbkey'