name: flake8

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  flake8:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python environment
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install flake8
      run: |
        python -m pip install flake8
    - name: Run flake8
      run: |
        flake8 . --max-line-length 200 --max-complexity = 15 --exclude docs/conf.py, tests/test_model.py --ignore = E203, E266, E501, W503
